# -*- coding: utf-8 -*-
"""chatgpt_API_Analyse_conversation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7QUhduKt3txpd7wKvJ30zblqyMBXAYi
"""

from openai import OpenAI
client = OpenAI(api_key="sk-proj-dSfBlLvnwQN52jwW5dmQT3BlbkFJXCqK1Dn2g5WdBc8ruZl4")

def analyze_conversation(conversation, skills):
    prompt = f"""
    Vous êtes un expert en analyse de recrutement. Veuillez analyser la conversation suivante entre un recruteur et un employé et expliquer pourquoi elle dysfonctionne en termes de compétences de l'employé.

    Conversation:
    {conversation}

    Compétences de l'employé:
    {skills}

    Veuillez structurer votre analyse comme suit :
    - Erreurs de l'employé : Identifiez et listez les erreurs spécifiques ou insuffisances dans les réponses de l'employé. Par exemple, une réponse vague ou un manque de détails.
    - Compétences manquantes : Listez les compétences qui manquent ou qui devraient être améliorées par l'employé en fonction de ce qui est attendu dans la conversation. Par exemple, des compétences techniques spécifiques ou des compétences en communication.
    - Conseils : Fournissez des conseils spécifiques à l'employé pour améliorer ses réponses lors des futurs entretiens. Incluez des suggestions sur la manière de mieux structurer ses réponses, d'apporter plus de détails concrets, et de montrer ses compétences pertinentes.

    Exemple d'analyse :
    Erreurs de l'employé :
    1. Vos réponses concernant les projets passés sont trop générales, vous manquez de détails spécifiques sur les résultats obtenus.
    2. Vous ne démontrez pas assez votre capacité à gérer des projets complexes avec des exemples précis.

    Compétences manquantes :
    1. Gestion de projets à grande échelle.
    2. Expérience en leadership et en coordination d'équipes.

    Conseils :
    1. Soyez prêt à discuter du salaire - Il est important de rechercher le salaire type pour le poste pour lequel vous postulez afin de pouvoir discuter de façon informée.
    2. Donnez des détails spécifiques - Lorsque vous parlez de vos expériences passées, essayez de donner des détails spécifiques tels que les résultats que vous avez obtenus, les défis que vous avez surmontés, et comment vous avez contribué au succès du projet.
    3. Mettez en avant vos compétences en gestion de projet - Si vous avez des compétences en gestion de projet, mettez-les en avant. Montrez comment vous avez géré les délais, les ressources et coordonné les équipes pour atteindre les objectifs du projet.
    4. Préparez des exemples concrets - Il est toujours utile d'avoir des exemples concrets à l'esprit pour illustrer vos compétences et votre expérience. Cela vous aidera à donner une réponse détaillée et précise lors des entretiens.
    """

    response = client.chat.completions.create(
        model="gpt-4",  # Utilisez le modèle approprié
        messages=[
            {"role": "system", "content": "You are an expert analyst."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000
    )

    return response.choices[0].message.content

# Fonction pour formater et diviser l'analyse
def format_analysis(analysis):
    sections = {
        "Erreurs de l'employé": "",
        "Compétences manquantes": "",
        "Conseils": ""
    }

    current_section = None

    for line in analysis.split('\n'):
        line = line.strip()
        if line.  startswith("Erreurs de l'employé :"):
            current_section = "Erreurs de l'employé"
        elif line.startswith("Compétences manquantes :"):
            current_section = "Compétences manquantes"
        elif line.startswith("Conseils :"):
            current_section = "Conseils"
        elif line == "":
            continue

        if current_section:
            sections[current_section] += line + "\n"

    return sections

# Exemple d'utilisation
conversation = """
Recruteur: Bonjour, merci d'avoir accepté cet entretien. Pouvez-vous vous présenter et me parler de votre parcours professionnel ?
Employé: Bonjour, je m'appelle Marc. J'ai travaillé pendant cinq ans en tant que développeur web chez XYZ Corp. J'ai principalement utilisé JavaScript et Python pour développer des applications web.
Recruteur: Pouvez-vous me donner un exemple de projet sur lequel vous avez travaillé et de votre rôle dans ce projet ?
Employé: Oui, j'ai travaillé sur une application de gestion de projet où j'étais responsable de la partie front-end. J'ai utilisé React pour créer une interface utilisateur dynamique.
Recruteur: Intéressant. Et quelles sont les technologies ou compétences que vous aimeriez approfondir ou apprendre à l'avenir ?
Employé: J'aimerais apprendre davantage sur le machine learning et l'intelligence artificielle.
Recruteur: Pouvez-vous décrire une situation où vous avez dû résoudre un problème complexe au travail ?
Employé: Une fois, nous avions un bug critique en production. J'ai dû passer toute la nuit à le corriger, et j'ai finalement trouvé que le problème venait d'une mauvaise gestion des états dans notre application React.
Recruteur: Comment gérez-vous le travail sous pression ?
Employé: Je fais de mon mieux pour rester calme et organisé. J'aime aussi prendre des pauses régulières pour éviter l'épuisement.
Recruteur: Avez-vous déjà travaillé en équipe ? Si oui, comment gérez-vous les conflits au sein de l'équipe ?
Employé: Oui, j'ai travaillé en équipe sur plusieurs projets. En cas de conflit, j'essaie toujours de communiquer ouvertement et de comprendre le point de vue de l'autre personne.
Recruteur: Quelles sont vos attentes salariales pour ce poste ?
Employé: J'aimerais discuter de cela une fois que nous aurons parlé plus en détail des responsabilités du poste et des attentes de l'entreprise.
Recruteur: Très bien, merci Marc. Nous reviendrons vers vous bientôt avec une réponse.
Employé: Merci à vous, bonne journée.
"""

skills = """
1. Développement web (JavaScript, Python)
2. Expérience avec React pour le front-end
3. Capacité à résoudre des problèmes complexes
4. Intérêt pour le machine learning et l'IA
5. Gestion du stress et du travail sous pression
6. Travail en équipe et gestion des conflits
"""

# Analyse de la conversation
analysis = analyze_conversation(conversation, skills)

# Formatage de l'analyse
formatted_analysis = format_analysis(analysis)

# Affichage des résultats
for section, content in formatted_analysis.items():
    print(f"### {section} ###\n{content}\n")

# another exemple

conversation2 ='''Recruteur: Bonjour, merci d'avoir accepté cet entretien. Pouvez-vous nous en dire plus sur votre expérience professionnelle jusqu'à présent ?
Employé: Bonjour, bien sûr. J'ai travaillé pendant trois ans en tant que spécialiste en marketing numérique chez ABC Company. J'ai géré plusieurs campagnes publicitaires en ligne et analysé les données pour optimiser les performances.
Recruteur: Intéressant. Quelles sont vos compétences principales dans le domaine du marketing numérique ?
Employé: Mes compétences principales comprennent la gestion de campagnes publicitaires sur les réseaux sociaux, l'optimisation du référencement (SEO) et l'analyse des données pour prendre des décisions stratégiques.
Recruteur: Parfait. Avez-vous déjà eu à gérer une crise de réputation en ligne ? Si oui, comment l'avez-vous gérée ?
Employé: Oui, j'ai eu une expérience de gestion de crise lorsqu'une campagne publicitaire controversée a suscité des réactions négatives sur les réseaux sociaux. J'ai réagi rapidement en publiant une déclaration officielle et en engageant la conversation avec les clients pour résoudre leurs préoccupations.
Recruteur: Très bien. Comment vous tenez-vous au courant des dernières tendances en marketing numérique ?
Employé: Je suis régulièrement des blogs et des webinaires sur le marketing numérique, je participe à des conférences de l'industrie et je suis actif sur les réseaux sociaux pour suivre les discussions et les nouvelles tendances.
Recruteur: Quelles sont vos attentes salariales pour ce poste ?
Employé: J'aimerais discuter de la rémunération une fois que nous aurons exploré plus en détail les responsabilités du poste et les avantages offerts par l'entreprise.
Recruteur: Très bien, merci pour ces informations. Nous vous recontacterons bientôt.
Employé: Merci à vous, bonne journée.
'''

skills2 ='''1. Gestion de campagnes publicitaires sur les réseaux sociaux
2. Optimisation du référencement (SEO)
3. Analyse des données pour prendre des décisions stratégiques
4. Gestion de crises de réputation en ligne
5. Veille constante des tendances en marketing numérique
'''


# Analyse de la conversation
analysis = analyze_conversation(conversation2, skills2)

# Formatage de l'analyse
formatted_analysis = format_analysis(analysis)

# Affichage des résultats
for section, content in formatted_analysis.items():
    print(f"### {section} ###\n{content}\n")

# version 2

"""# version 2"""

# améliorer le code encore
'''
Contexte du Poste : Ajout de la description du poste pour mieux cibler l'analyse.

Critères d'Évaluation : Énumération des critères spécifiques pour l'évaluation.

Structure Détaillée : Clarification des attentes pour chaque section d'analyse.

Feedback Positif : Inclusion de points positifs pour un retour équilibré.

Suggestions de Questions : Proposition de questions que l'employé pourrait poser au recruteur.

Simulation de Réponses : Fourniture d'exemples de réponses améliorées pour guider l'employé.

'''

def analyze_conversation2(conversation, skills, job_description):
    prompt = f"""
    Vous êtes un expert en analyse de recrutement. Veuillez analyser la conversation suivante entre un recruteur et un employé et expliquer pourquoi elle dysfonctionne en termes de compétences de l'employé.

    Conversation:
    {conversation}

    Compétences de l'employé:
    {skills}

    Description du poste:
    {job_description}

    Veuillez structurer votre analyse comme suit :
    - Erreurs de l'employé : Identifiez et listez les erreurs spécifiques ou insuffisances dans les réponses de l'employé.
    - Compétences manquantes : Listez les compétences qui manquent ou qui devraient être améliorées par l'employé en fonction des attentes pour ce poste.
    - Feedback positif : Soulignez les aspects positifs dans les réponses de l'employé.
    - Conseils : Fournissez des conseils spécifiques pour améliorer les réponses de l'employé lors des futurs entretiens. Incluez des suggestions sur la manière de mieux structurer ses réponses, d'apporter plus de détails concrets, et de montrer ses compétences pertinentes.
    - Suggestions de questions : Proposez des questions que l'employé pourrait poser au recruteur pour mieux comprendre le poste et montrer son intérêt.
    - Simulation de réponses : Fournissez des exemples de réponses améliorées pour les questions spécifiques posées par le recruteur.

    Exemple d'analyse :
    Erreurs de l'employé :
    1. Vos réponses concernant les projets passés sont trop générales, vous manquez de détails spécifiques sur les résultats obtenus.
    2. Vous ne démontrez pas assez votre capacité à gérer des projets complexes avec des exemples précis.

    Compétences manquantes :
    1. Gestion de projets à grande échelle.
    2. Expérience en leadership et en coordination d'équipes.

    Feedback positif :
    1. Vous avez montré une bonne connaissance de JavaScript et Python.
    2. Vous avez bien expliqué votre rôle dans le développement front-end avec React.

    Conseils :
    1. Soyez prêt à discuter du salaire - Il est important de rechercher le salaire type pour le poste pour lequel vous postulez afin de pouvoir discuter de façon informée.
    2. Donnez des détails spécifiques - Lorsque vous parlez de vos expériences passées, essayez de donner des détails spécifiques tels que les résultats que vous avez obtenus, les défis que vous avez surmontés, et comment vous avez contribué au succès du projet.
    3. Mettez en avant vos compétences en gestion de projet - Si vous avez des compétences en gestion de projet, mettez-les en avant. Montrez comment vous avez géré les délais, les ressources et coordonné les équipes pour atteindre les objectifs du projet.
    4. Préparez des exemples concrets - Il est toujours utile d'avoir des exemples concrets à l'esprit pour illustrer vos compétences et votre expérience. Cela vous aidera à donner une réponse détaillée et précise lors des entretiens.

    Suggestions de questions :
    1. Pouvez-vous me parler des objectifs principaux de ce poste et des défis que je pourrais rencontrer ?
    2. Quelles sont les opportunités de développement professionnel au sein de votre entreprise ?
    3. Comment décririez-vous la culture d'entreprise ici ?

    Simulation de réponses :
    Question : Pouvez-vous me donner un exemple de projet sur lequel vous avez travaillé et de votre rôle dans ce projet ?
    Réponse améliorée : Oui, j'ai travaillé sur une application de gestion de projet où j'étais responsable de la partie front-end. J'ai utilisé React pour créer une interface utilisateur dynamique. Un des défis principaux était de garantir une expérience utilisateur fluide malgré la complexité des fonctionnalités. J'ai implémenté une gestion efficace des états avec Redux, ce qui a permis de réduire les temps de réponse de 20% et d'améliorer la satisfaction des utilisateurs finaux. Le projet a été livré dans les délais et a reçu des retours très positifs.
    """

    response = client.chat.completions.create(
        model="gpt-4",  # Utilisez le modèle approprié

        messages=[
            {"role": "system", "content": "You are an expert analyst."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=2000
    )

    return response.choices[0].message.content

def format_analysis(analysis):
    sections = ["Erreurs de l'employé", "Compétences manquantes", "Feedback positif", "Conseils", "Suggestions de questions", "Simulation de réponses"]
    formatted_analysis = {section: "" for section in sections}

    current_section = None
    for line in analysis.split('\n'):
        if any(section in line for section in sections):
            current_section = next(section for section in sections if section in line)
        elif current_section:
            formatted_analysis[current_section] += line + "\n"

    return formatted_analysis

# Exemple d'utilisation
conversation = """
Recruteur: Bonjour, merci d'avoir accepté cet entretien. Pouvez-vous vous présenter et me parler de votre parcours professionnel ?
Employé: Bonjour, je m'appelle Marc. J'ai travaillé pendant cinq ans en tant que développeur web chez XYZ Corp. J'ai principalement utilisé JavaScript et Python pour développer des applications web.
Recruteur: Pouvez-vous me donner un exemple de projet sur lequel vous avez travaillé et de votre rôle dans ce projet ?
Employé: Oui, j'ai travaillé sur une application de gestion de projet où j'étais responsable de la partie front-end. J'ai utilisé React pour créer une interface utilisateur dynamique.
Recruteur: Intéressant. Et quelles sont les technologies ou compétences que vous aimeriez approfondir ou apprendre à l'avenir ?
Employé: J'aimerais apprendre davantage sur le machine learning et l'intelligence artificielle.
Recruteur: Pouvez-vous décrire une situation où vous avez dû résoudre un problème complexe au travail ?
Employé: Une fois, nous avions un bug critique en production. J'ai dû passer toute la nuit à le corriger, et j'ai finalement trouvé que le problème venait d'une mauvaise gestion des états dans notre application React.
Recruteur: Comment gérez-vous le travail sous pression ?
Employé: Je fais de mon mieux pour rester calme et organisé. J'aime aussi prendre des pauses régulières pour éviter l'épuisement.
Recruteur: Avez-vous déjà travaillé en équipe ? Si oui, comment gérez-vous les conflits au sein de l'équipe ?
Employé: Oui, j'ai travaillé en équipe sur plusieurs projets. En cas de conflit, j'essaie toujours de communiquer ouvertement et de comprendre le point de vue de l'autre personne.
Recruteur: Quelles sont vos attentes salariales pour ce poste ?
Employé: J'aimerais discuter de cela une fois que nous aurons parlé plus en détail des responsabilités du poste et des attentes de l'entreprise.
Recruteur: Très bien, merci Marc. Nous reviendrons vers vous bientôt avec une réponse.
Employé: Merci à vous, bonne journée.
"""

skills = """
1. Développement web (JavaScript, Python)
2. Expérience avec React pour le front-end
3. Capacité à résoudre des problèmes complexes
4. Intérêt pour le machine learning et l'IA
5. Gestion du stress et du travail sous pression
6. Travail en équipe et gestion des conflits
"""

job_description = """
Poste : Développeur Full Stack
Compétences requises : Développement web, gestion de projets, collaboration en équipe, capacité à résoudre des problèmes complexes, connaissance en machine learning et IA, expérience avec React et Node.js.
"""

# Analyse de la conversation
analysis = analyze_conversation2(conversation, skills, job_description)

# Formater et afficher l'analyse
formatted_analysis = format_analysis(analysis)
for section, content in formatted_analysis.items():
    print(f"### {section} ###")
    print(content.strip())
    print()

# exemple 2 domaine dans   marketing digital.

conversation = """
Recruteur: Bonjour, merci d'avoir accepté cet entretien. Pouvez-vous vous présenter et me parler de votre parcours professionnel ?
Employé: Bonjour, je m'appelle Anna. J'ai travaillé pendant quatre ans en tant que spécialiste du marketing digital chez Digital Media Solutions, où j'ai géré des campagnes de publicité en ligne et optimisé les performances SEO.
Recruteur: Pouvez-vous me donner un exemple de campagne marketing sur laquelle vous avez travaillé et de votre rôle dans cette campagne ?
Employé: Oui, j'ai dirigé une campagne publicitaire pour le lancement d'un nouveau produit. J'étais responsable de la stratégie de marketing de contenu, de la gestion des publicités sur les réseaux sociaux et de l'analyse des performances des campagnes.
Recruteur: Quelles compétences techniques aimeriez-vous développer davantage ?
Employé: J'aimerais approfondir mes compétences en marketing automation et en analyse de données avec des outils comme Google Analytics et HubSpot.
Recruteur: Pouvez-vous décrire une situation où vous avez dû résoudre un problème complexe au travail ?
Employé: Une fois, nous avons constaté une baisse soudaine du trafic sur notre site web. J'ai analysé les données SEO et découvert que la baisse était due à une mise à jour de l'algorithme de Google. J'ai ensuite mis en place une stratégie pour améliorer notre classement.
Recruteur: Comment gérez-vous les délais serrés et le stress ?
Employé: Je planifie mes tâches en fonction des priorités et je m'assure de prendre des pauses régulières pour rester concentrée et éviter l'épuisement.
Recruteur: Avez-vous déjà travaillé en équipe ? Si oui, comment gérez-vous les conflits au sein de l'équipe ?
Employé: Oui, j'ai souvent travaillé avec des équipes interfonctionnelles. En cas de conflit, j'organise des réunions pour discuter des problèmes et trouver des solutions qui conviennent à tout le monde.
Recruteur: Quelles sont vos attentes salariales pour ce poste ?
Employé: J'aimerais discuter du salaire après avoir mieux compris les responsabilités du poste et les attentes de l'entreprise.
Recruteur: Merci Anna. Nous vous recontacterons bientôt avec notre décision.
Employé: Merci pour cette opportunité, bonne journée.

"""

skills = """
1. Gestion de campagnes publicitaires en ligne
2. Optimisation SEO
3. Marketing de contenu
4. Analyse de performances des campagnes
5. Marketing automation
6. Analyse de données (Google Analytics, HubSpot)
7. Gestion du stress et des délais serrés
8. Collaboration inter-équipes et résolution de conflits

"""

job_description = """
Poste : Responsable Marketing Digital
Compétences requises : Gestion de campagnes publicitaires, SEO, marketing de contenu, marketing automation, analyse de données, compétences en communication, capacité à travailler sous pression, collaboration inter-équipes.
"""

# Analyse de la conversation
analysis = analyze_conversation2(conversation, skills, job_description)

# Formater et afficher l'analyse
formatted_analysis = format_analysis(analysis)
for section, content in formatted_analysis.items():
    print(f"### {section} ###")
    print(content.strip())
    print()



"""# test les autres models  


"""

def analyze_conversation2(conversation, skills, job_description):
    prompt = f"""
    Vous êtes un expert en analyse de recrutement. Veuillez analyser la conversation suivante entre un recruteur et un employé et expliquer pourquoi elle dysfonctionne en termes de compétences de l'employé.

    Conversation:
    {conversation}

    Compétences de l'employé:
    {skills}

    Description du poste:
    {job_description}

    Veuillez structurer votre analyse comme suit :
    - Erreurs de l'employé : Identifiez et listez les erreurs spécifiques ou insuffisances dans les réponses de l'employé.
    - Compétences manquantes : Listez les compétences qui manquent ou qui devraient être améliorées par l'employé en fonction des attentes pour ce poste.
    - Feedback positif : Soulignez les aspects positifs dans les réponses de l'employé.
    - Conseils : Fournissez des conseils spécifiques pour améliorer les réponses de l'employé lors des futurs entretiens. Incluez des suggestions sur la manière de mieux structurer ses réponses, d'apporter plus de détails concrets, et de montrer ses compétences pertinentes.
    - Suggestions de questions : Proposez des questions que l'employé pourrait poser au recruteur pour mieux comprendre le poste et montrer son intérêt.
    - Simulation de réponses : Fournissez des exemples de réponses améliorées pour les questions spécifiques posées par le recruteur.

    Exemple d'analyse :
    Erreurs de l'employé :
    1. Vos réponses concernant les projets passés sont trop générales, vous manquez de détails spécifiques sur les résultats obtenus.
    2. Vous ne démontrez pas assez votre capacité à gérer des projets complexes avec des exemples précis.

    Compétences manquantes :
    1. Gestion de projets à grande échelle.
    2. Expérience en leadership et en coordination d'équipes.

    Feedback positif :
    1. Vous avez montré une bonne connaissance de JavaScript et Python.
    2. Vous avez bien expliqué votre rôle dans le développement front-end avec React.

    Conseils :
    1. Soyez prêt à discuter du salaire - Il est important de rechercher le salaire type pour le poste pour lequel vous postulez afin de pouvoir discuter de façon informée.
    2. Donnez des détails spécifiques - Lorsque vous parlez de vos expériences passées, essayez de donner des détails spécifiques tels que les résultats que vous avez obtenus, les défis que vous avez surmontés, et comment vous avez contribué au succès du projet.
    3. Mettez en avant vos compétences en gestion de projet - Si vous avez des compétences en gestion de projet, mettez-les en avant. Montrez comment vous avez géré les délais, les ressources et coordonné les équipes pour atteindre les objectifs du projet.
    4. Préparez des exemples concrets - Il est toujours utile d'avoir des exemples concrets à l'esprit pour illustrer vos compétences et votre expérience. Cela vous aidera à donner une réponse détaillée et précise lors des entretiens.

    Suggestions de questions :
    1. Pouvez-vous me parler des objectifs principaux de ce poste et des défis que je pourrais rencontrer ?
    2. Quelles sont les opportunités de développement professionnel au sein de votre entreprise ?
    3. Comment décririez-vous la culture d'entreprise ici ?

    Simulation de réponses :
    Question : Pouvez-vous me donner un exemple de projet sur lequel vous avez travaillé et de votre rôle dans ce projet ?
    Réponse améliorée : Oui, j'ai travaillé sur une application de gestion de projet où j'étais responsable de la partie front-end. J'ai utilisé React pour créer une interface utilisateur dynamique. Un des défis principaux était de garantir une expérience utilisateur fluide malgré la complexité des fonctionnalités. J'ai implémenté une gestion efficace des états avec Redux, ce qui a permis de réduire les temps de réponse de 20% et d'améliorer la satisfaction des utilisateurs finaux. Le projet a été livré dans les délais et a reçu des retours très positifs.
    """

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",

        messages=[
            {"role": "system", "content": "You are an expert analyst."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=2000
    )

    return response.choices[0].message.content

def format_analysis(analysis):
    sections = ["Erreurs de l'employé", "Compétences manquantes", "Feedback positif", "Conseils", "Suggestions de questions", "Simulation de réponses"]
    formatted_analysis = {section: "" for section in sections}

    current_section = None
    for line in analysis.split('\n'):
        if any(section in line for section in sections):
            current_section = next(section for section in sections if section in line)
        elif current_section:
            formatted_analysis[current_section] += line + "\n"

    return formatted_analysis

# Exemple d'utilisation 1
conversation = """
Recruteur: Bonjour, merci d'avoir accepté cet entretien. Pouvez-vous vous présenter et me parler de votre parcours professionnel ?
Employé: Bonjour, je m'appelle Marc. J'ai travaillé pendant cinq ans en tant que développeur web chez XYZ Corp. J'ai principalement utilisé JavaScript et Python pour développer des applications web.
Recruteur: Pouvez-vous me donner un exemple de projet sur lequel vous avez travaillé et de votre rôle dans ce projet ?
Employé: Oui, j'ai travaillé sur une application de gestion de projet où j'étais responsable de la partie front-end. J'ai utilisé React pour créer une interface utilisateur dynamique.
Recruteur: Intéressant. Et quelles sont les technologies ou compétences que vous aimeriez approfondir ou apprendre à l'avenir ?
Employé: J'aimerais apprendre davantage sur le machine learning et l'intelligence artificielle.
Recruteur: Pouvez-vous décrire une situation où vous avez dû résoudre un problème complexe au travail ?
Employé: Une fois, nous avions un bug critique en production. J'ai dû passer toute la nuit à le corriger, et j'ai finalement trouvé que le problème venait d'une mauvaise gestion des états dans notre application React.
Recruteur: Comment gérez-vous le travail sous pression ?
Employé: Je fais de mon mieux pour rester calme et organisé. J'aime aussi prendre des pauses régulières pour éviter l'épuisement.
Recruteur: Avez-vous déjà travaillé en équipe ? Si oui, comment gérez-vous les conflits au sein de l'équipe ?
Employé: Oui, j'ai travaillé en équipe sur plusieurs projets. En cas de conflit, j'essaie toujours de communiquer ouvertement et de comprendre le point de vue de l'autre personne.
Recruteur: Quelles sont vos attentes salariales pour ce poste ?
Employé: J'aimerais discuter de cela une fois que nous aurons parlé plus en détail des responsabilités du poste et des attentes de l'entreprise.
Recruteur: Très bien, merci Marc. Nous reviendrons vers vous bientôt avec une réponse.
Employé: Merci à vous, bonne journée.
"""

skills = """
1. Développement web (JavaScript, Python)
2. Expérience avec React pour le front-end
3. Capacité à résoudre des problèmes complexes
4. Intérêt pour le machine learning et l'IA
5. Gestion du stress et du travail sous pression
6. Travail en équipe et gestion des conflits
"""

job_description = """
Poste : Développeur Full Stack
Compétences requises : Développement web, gestion de projets, collaboration en équipe, capacité à résoudre des problèmes complexes, connaissance en machine learning et IA, expérience avec React et Node.js.
"""

# Analyse de la conversation
analysis = analyze_conversation2(conversation, skills, job_description)

# Formater et afficher l'analyse
formatted_analysis = format_analysis(analysis)
for section, content in formatted_analysis.items():
    print(f"### {section} ###")
    print(content.strip())
    print()

# exemple 2 domaine dans   marketing digital.

conversation = """
Recruteur: Bonjour, merci d'avoir accepté cet entretien. Pouvez-vous vous présenter et me parler de votre parcours professionnel ?
Employé: Bonjour, je m'appelle Anna. J'ai travaillé pendant quatre ans en tant que spécialiste du marketing digital chez Digital Media Solutions, où j'ai géré des campagnes de publicité en ligne et optimisé les performances SEO.
Recruteur: Pouvez-vous me donner un exemple de campagne marketing sur laquelle vous avez travaillé et de votre rôle dans cette campagne ?
Employé: Oui, j'ai dirigé une campagne publicitaire pour le lancement d'un nouveau produit. J'étais responsable de la stratégie de marketing de contenu, de la gestion des publicités sur les réseaux sociaux et de l'analyse des performances des campagnes.
Recruteur: Quelles compétences techniques aimeriez-vous développer davantage ?
Employé: J'aimerais approfondir mes compétences en marketing automation et en analyse de données avec des outils comme Google Analytics et HubSpot.
Recruteur: Pouvez-vous décrire une situation où vous avez dû résoudre un problème complexe au travail ?
Employé: Une fois, nous avons constaté une baisse soudaine du trafic sur notre site web. J'ai analysé les données SEO et découvert que la baisse était due à une mise à jour de l'algorithme de Google. J'ai ensuite mis en place une stratégie pour améliorer notre classement.
Recruteur: Comment gérez-vous les délais serrés et le stress ?
Employé: Je planifie mes tâches en fonction des priorités et je m'assure de prendre des pauses régulières pour rester concentrée et éviter l'épuisement.
Recruteur: Avez-vous déjà travaillé en équipe ? Si oui, comment gérez-vous les conflits au sein de l'équipe ?
Employé: Oui, j'ai souvent travaillé avec des équipes interfonctionnelles. En cas de conflit, j'organise des réunions pour discuter des problèmes et trouver des solutions qui conviennent à tout le monde.
Recruteur: Quelles sont vos attentes salariales pour ce poste ?
Employé: J'aimerais discuter du salaire après avoir mieux compris les responsabilités du poste et les attentes de l'entreprise.
Recruteur: Merci Anna. Nous vous recontacterons bientôt avec notre décision.
Employé: Merci pour cette opportunité, bonne journée.

"""

skills = """
1. Gestion de campagnes publicitaires en ligne
2. Optimisation SEO
3. Marketing de contenu
4. Analyse de performances des campagnes
5. Marketing automation
6. Analyse de données (Google Analytics, HubSpot)
7. Gestion du stress et des délais serrés
8. Collaboration inter-équipes et résolution de conflits

"""

job_description = """
Poste : Responsable Marketing Digital
Compétences requises : Gestion de campagnes publicitaires, SEO, marketing de contenu, marketing automation, analyse de données, compétences en communication, capacité à travailler sous pression, collaboration inter-équipes.
"""

# Analyse de la conversation
analysis = analyze_conversation2(conversation, skills, job_description)

# Formater et afficher l'analyse
formatted_analysis = format_analysis(analysis)
for section, content in formatted_analysis.items():
    print(f"### {section} ###")
    print(content.strip())
    print()

